### ISSUE TITLE
Release statements after consuming result sets

### ISSUE THREAD

**Issue by dlindenkreuz** [elixir-explorer/adbc#50]
The ADBC spec suggests to always [release the query statement](https://arrow.apache.org/adbc/main/format/specification.html#basic-usage) after result sets have been consumed. Judging by the illustration, it looks like `prepare` is optional, but `release` is not.

Currently, the Elixir ADBC implementation only releases the result streams, but not the statements. Is this intentional?

**Comment by josevalim** [comment]
Don’t we automatically release it once it is garbage collected?

**Comment by dlindenkreuz** [comment]
Disclaimer: I am fairly new to NIFs. Please excuse me if I am completely off.

From what I can tell, yes, the value, schema and NifRes objects are [autoreleased on the C++ side](https://github.com/elixir-explorer/adbc/blob/main/c_src/adbc_nif_resource.hpp#L111), but (prepared) queries should be released explicitly on the ADBC driver / database side as well. At least I haven't seen any calls to `adbc_statement_release` in this context.

I did a really dumb test and added `throw std::runtime_error("boom")` inside `adbc_statement_release` to find that this function never crashes if not explicitly called by the user.

The ADBC driver implementation for SQLite [frees the stored compiled bytecode via `sqlite_finalize`](https://github.com/apache/arrow-adbc/blob/main/c/driver/sqlite/sqlite.c#L1107) when the statement is released explicitly.

This likely means that while the Erlang refs and other wrappers are indeed freed, the actual queries behind them are not freed on the DB end. Maybe databases do GC or otherwise evict their prepared query caches, but it would be great if one could release prepared queries sooner if there's a defined lifetime. SQLite also exposes [`sqlite_finalize`](https://www.sqlite.org/c3ref/finalize.html) for this purpose.

I assume this needs to happen in "userland" if ADBC exposes explicit release functions. But maybe I missed something?

**Comment by josevalim** [comment]
I believe you are right. Here is the code invoked when a resource is deleted:

https://github.com/elixir-explorer/adbc/blob/2081c6e3824850623bb2466d1a84abd8a04de173/c_src/adbc_nif_resource.hpp#L110-L127

However, that does not match AdbcStatementRelease implemention:

https://github.com/apache/arrow-adbc/blob/9544887f37edc30bed43a93ee4be615df3f1b014/c/driver_manager/adbc_driver_manager.cc#L1450-L1459

We could add a new clause that checks for private_driver, reproducing AdbcStatementRelease, but I think that, instead of using C++ templates, maybe we should define a clause for each type? This way we can guarantee everything is released properly by the GC instead of relying on Elixir code.

Thoughts @cocoa-xu?

**Comment by josevalim** [comment]
Doing this change will be specially important for prepared statement, as it then becomes the user responsibility to manage them.

**Comment by josevalim** [comment]
Fixed with #53.
